// Authentication constants
export const USER_LOADING = 'USER_LOADING'; 
export const USER_LOADED = 'USER_LOADED'; 
export const AUTH_ERROR = 'AUTH_ERROR'; 
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'; 
export const REGISTER_FAIL = 'REGISTER_FAIL'; 
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'; 
export const LOGIN_FAIL = 'LOGIN_FAIL'; 
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'; 

// The Movie Database search constants
export const MOVIE_RESULTS_LOADING = 'MOVIE_RESULTS_LOADING';
export const MOVIE_RESULTS_LOADED = 'MOVIE_RESULTS_LOADED'; 
export const SERIES_RESULTS_LOADING = 'SERIES_RESULTS_LOADING'; 
export const SERIES_RESULTS_LOADED = 'SERIES_RESULTS_LOADED'; 
export const SEARCH_FAIL = 'SEARCH_FAIL'; 

// The Movie Database get constants
export const MOVIE_LOADING = 'MOVIE_LOADING';
export const MOVIE_LOADED = 'MOVIE_LOADED'; 
export const SERIES_LOADING = 'SERIES_LOADING'; 
export const SERIES_LOADED = 'SERIES_LOADED'; 
export const MEDIA_DETAILS_FAIL = 'MEDIA_DETAILS_FAIL'; 

//list details 
export const LIST_DETAILS_LOADING = 'LIST_DETAILS_LOADING';
export const LIST_DETAILS_LOADED = 'LIST_DETAILS_LOADED';
export const LIST_DETAILS_FAIL = 'LIST_DETAILS_FAIL';

//list constants
export const WANT_TO_WATCH_LOADED = "WANT_TO_WATCH_LOADED";
export const HAVE_WATCHED_LOADED  = "HAVE_WATCHED_LOADED";
export const WANT_TO_WATCH_LOADING = "WANT_TO_WATCH_LOADING";
export const HAVE_WATCHED_LOADING = "HAVE_WATCHED_LOADING";
export const ADD_WANT_TO_WATCH = "ADD_WANT_TO_WATCH";
export const ADD_HAVE_WATCHED = "ADD_HAVE_WATCHED";
export const DELETE_WANT_TO_WATCH = "DELETE_WANT_TO_WATCH";
export const DELETE_HAVE_WATCHED = "DELETE_HAVE_WATCHED";
export const WANT_TO_WATCH_FAILED = "WANT_TO_WATCH_FAILED";
export const HAVE_WATCHED_FAILED = "HAVE_WATCHED_FAILED";

